import type { MetadataRoute } from 'next';
import { SITE_ORIGIN } from '@/data/chrome-seo';

/**
 * Dynamic robots.txt — replaces the old static public/robots.txt so the
 * sitemap URL stays in sync with whatever host we're deployed on and so
 * future per-user-agent rules can live alongside the rest of the SEO
 * surface.
 *
 * Rules:
 *   - Everything under `/` is crawlable by default.
 *   - `/admin` and `/api` are disallowed (admin UI + internal routes
 *     that shouldn't appear in search).
 *   - The sitemap lives at `${SITE_ORIGIN}/sitemap.xml` (generated by
 *     src/app/sitemap.ts). Pointing crawlers at it speeds up discovery.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/admin', '/api'],
      },
    ],
    sitemap: `${SITE_ORIGIN}/sitemap.xml`,
    host: SITE_ORIGIN,
  };
}
